/**
 * vscode-theme-extended — coverage for VS Code surfaces the base theme
 * did not previously style.
 *
 * The base `buildVscodeThemeJson` styles the classic workbench. Modern VS Code
 * registers ~940 themable colors; anything a theme leaves unset falls back to
 * VS Code's built-in Dark+ defaults, which clash with Caligo's OKLCH palette.
 * This module derives the remaining keys from the same palette roles so every
 * surface stays perceptually consistent.
 *
 * Deliberately NOT covered:
 *  - `contrastBorder` / `contrastActiveBorder` — high-contrast themes only.
 *    Setting them in a normal dark theme outlines every widget.
 *  - `myWidget.*` — a documentation example, not a real VS Code color.
 */

import { withAlpha } from "./color.js";
import type { DerivedPalette } from "./palette.js";

export function buildExtendedColors(p: DerivedPalette): Record<string, string> {
  const s = p.semantic;

  // Shared derivations -------------------------------------------------------
  const surface = p.bg1;
  const surfaceHigh = p.bg2;
  const subtleBorder = withAlpha(p.border, 0.6);
  const hoverBg = withAlpha(p.accent, 0.12);
  const activeBg = withAlpha(p.accent, 0.18);
  const dropBg = withAlpha(p.accent, 0.16);
  /** Fully transparent, derived from the palette (never literal #000000). */
  const transparent = withAlpha(p.bg0, 0);
  const shadow = withAlpha(p.bg0, 0.5);

  /** Diff/merge tints: strong enough to read, weak enough to keep text legible. */
  const addedBg = withAlpha(s.success, 0.16);
  const addedLine = withAlpha(s.success, 0.1);
  const removedBg = withAlpha(s.error, 0.16);
  const removedLine = withAlpha(s.error, 0.1);

  return {
    // ── Activity Bar ────────────────────────────────────────────────────────
    "activityBar.activeBackground": withAlpha(p.accent, 0.1),
    "activityBar.activeFocusBorder": p.accent,
    "activityBar.border": p.border,
    "activityBar.dropBorder": p.accent,
    "activityBarBadge.background": p.accent,
    "activityBarBadge.foreground": p.bg0,
    "activityErrorBadge.background": s.error,
    "activityErrorBadge.foreground": p.bg0,
    "activityWarningBadge.background": s.warning,
    "activityWarningBadge.foreground": p.bg0,
    "activityBarTop.background": surface,
    "activityBarTop.foreground": p.fg1,
    "activityBarTop.inactiveForeground": p.fgMuted,
    "activityBarTop.activeBackground": withAlpha(p.accent, 0.1),
    "activityBarTop.activeBorder": p.accent,
    "activityBarTop.dropBorder": p.accent,
    "sideBarActivityBarTop.border": p.border,
    "modernActivityBar.activeBackground": activeBg,
    "modernActivityBar.activeForeground": p.accent,
    "modernActivityBar.hoverBackground": hoverBg,
    "modernActivityBar.hoverForeground": p.fg0,

    // ── Action bar / toolbar / keybindings ─────────────────────────────────
    "actionBar.toggledBackground": activeBg,
    "toolbar.hoverBackground": hoverBg,
    "toolbar.hoverOutline": withAlpha(p.accent, 0.5),
    "toolbar.activeBackground": activeBg,
    "keybindingLabel.background": withAlpha(p.fg0, 0.07),
    "keybindingLabel.foreground": p.fg1,
    "keybindingLabel.border": subtleBorder,
    "keybindingLabel.bottomBorder": p.border,
    "keybindingTable.headerBackground": surfaceHigh,
    "keybindingTable.rowsBackground": surface,

    // ── Banner / breadcrumbs ───────────────────────────────────────────────
    "banner.background": surfaceHigh,
    "banner.foreground": p.fg0,
    "banner.iconForeground": p.accent,
    "breadcrumb.background": p.bg0,
    "breadcrumb.foreground": p.fgMuted,
    "breadcrumb.focusForeground": p.fg0,
    "breadcrumb.activeSelectionForeground": p.accent,
    "breadcrumbPicker.background": surfaceHigh,

    // ── Buttons / inputs / radio / checkbox ────────────────────────────────
    "button.border": withAlpha(p.accent, 0.5),
    "button.secondaryBorder": subtleBorder,
    "button.separator": withAlpha(p.bg0, 0.4),
    "input.border": p.border,
    "inputOption.activeBackground": activeBg,
    "inputOption.activeBorder": p.accent,
    "inputOption.activeForeground": p.fg0,
    "inputOption.hoverBackground": hoverBg,
    "inputValidation.errorBackground": s.errorBg,
    "inputValidation.errorForeground": p.fg0,
    "inputValidation.errorBorder": s.error,
    "inputValidation.warningBackground": s.warningBg,
    "inputValidation.warningForeground": p.fg0,
    "inputValidation.warningBorder": s.warning,
    "inputValidation.infoBackground": s.infoBg,
    "inputValidation.infoForeground": p.fg0,
    "inputValidation.infoBorder": s.info,
    "checkbox.selectBackground": surfaceHigh,
    "checkbox.selectBorder": p.accent,
    "checkbox.disabled.background": withAlpha(p.fgMuted, 0.12),
    "checkbox.disabled.foreground": withAlpha(p.fgMuted, 0.5),
    "radio.activeBackground": activeBg,
    "radio.activeBorder": p.accent,
    "radio.activeForeground": p.fg0,
    "radio.inactiveBackground": withAlpha(p.fg0, 0.05),
    "radio.inactiveBorder": p.border,
    "radio.inactiveForeground": p.fgMuted,
    "radio.inactiveHoverBackground": hoverBg,

    // ── Command Center / window / title bar ───────────────────────────────
    "commandCenter.background": surface,
    "commandCenter.foreground": p.fg1,
    "commandCenter.border": p.border,
    "commandCenter.activeBackground": activeBg,
    "commandCenter.activeForeground": p.fg0,
    "commandCenter.activeBorder": p.accent,
    "commandCenter.inactiveBorder": subtleBorder,
    "commandCenter.inactiveForeground": p.fgMuted,
    "commandCenter.debuggingBackground": withAlpha(p.hueOrange, 0.2),
    "titleBar.border": p.border,
    "window.activeBorder": p.border,
    "window.inactiveBorder": subtleBorder,
    "widget.border": p.border,

    // ── Editor: find / highlight / snippets / ghost text ──────────────────
    "editor.border": p.border,
    "editor.compositionBorder": p.accent,
    "editor.findMatchForeground": p.fg0,
    "editor.findMatchHighlightForeground": p.fg0,
    "editor.findMatchHighlightBorder": withAlpha(p.accent, 0.4),
    "editor.findRangeHighlightBackground": withAlpha(p.accent, 0.08),
    "editor.findRangeHighlightBorder": withAlpha(p.accent, 0.2),
    "editor.hoverHighlightBackground": withAlpha(p.accent, 0.14),
    "editor.inactiveLineHighlightBackground": withAlpha(p.fg0, 0.03),
    "editor.lineHighlightBorder": withAlpha(p.accent, 0.12),
    "editor.rangeHighlightBackground": withAlpha(p.accent, 0.1),
    "editor.rangeHighlightBorder": withAlpha(p.accent, 0.22),
    "editor.selectionForeground": p.fg0,
    "editor.selectionHighlightBorder": withAlpha(p.accent, 0.3),
    "editor.symbolHighlightBackground": withAlpha(p.hueYellow, 0.18),
    "editor.symbolHighlightBorder": withAlpha(p.hueYellow, 0.4),
    "editor.wordHighlightBorder": withAlpha(p.accent, 0.3),
    "editor.wordHighlightStrongBorder": withAlpha(p.accentSoft, 0.4),
    "editor.wordHighlightTextBackground": withAlpha(p.fg0, 0.07),
    "editor.wordHighlightTextBorder": withAlpha(p.fg0, 0.2),
    "editor.snippetTabstopHighlightBackground": withAlpha(p.accent, 0.14),
    "editor.snippetTabstopHighlightBorder": withAlpha(p.accent, 0.3),
    "editor.snippetFinalTabstopHighlightBackground": withAlpha(p.hueGreen, 0.14),
    "editor.snippetFinalTabstopHighlightBorder": withAlpha(p.hueGreen, 0.35),
    "editor.foldPlaceholderForeground": p.fgMuted,
    "editor.inlineValuesBackground": withAlpha(p.hueYellow, 0.1),
    "editor.inlineValuesForeground": withAlpha(p.fg1, 0.85),
    "editor.placeholder.foreground": withAlpha(p.fgMuted, 0.7),
    "editorPane.background": p.bg0,
    "editorCursor.background": p.bg0,
    "editorRuler.foreground": withAlpha(p.border, 0.7),
    "editorCodeLens.foreground": withAlpha(p.fgMuted, 0.85),
    "editorLineNumber.dimmedForeground": withAlpha(p.fgMuted, 0.35),
    "editorActiveLineNumber.foreground": withAlpha(p.fg0, 0.8),
    "editorBracketMatch.foreground": p.accentSoft,
    "editorLink.activeForeground": p.accent,
    "editorGhostText.foreground": withAlpha(p.fgMuted, 0.65),
    "editorGhostText.background": transparent,
    "editorGhostText.border": transparent,
    "editorUnicodeHighlight.background": withAlpha(p.hueOrange, 0.14),
    "editorUnicodeHighlight.border": s.warning,
    "editorMultiCursor.primary.foreground": p.accentSoft,
    "editorMultiCursor.primary.background": p.bg0,
    "editorMultiCursor.secondary.foreground": withAlpha(p.accentSoft, 0.7),
    "editorMultiCursor.secondary.background": p.bg0,

    // ── Editor diagnostics ────────────────────────────────────────────────
    "editorError.foreground": s.error,
    "editorError.background": withAlpha(s.error, 0.08),
    "editorError.border": transparent,
    "editorWarning.background": withAlpha(s.warning, 0.08),
    "editorWarning.border": transparent,
    "editorInfo.foreground": s.info,
    "editorInfo.background": withAlpha(s.info, 0.08),
    "editorInfo.border": transparent,
    "editorHint.foreground": withAlpha(p.fgMuted, 0.8),
    "editorHint.border": transparent,
    "editorLightBulb.foreground": s.warning,
    "editorLightBulbAutoFix.foreground": s.success,
    "editorLightBulbAi.foreground": p.huePurple,

    // ── Editor gutter ─────────────────────────────────────────────────────
    "editorGutter.background": p.bg0,
    "editorGutter.addedBackground": s.success,
    "editorGutter.modifiedBackground": s.info,
    "editorGutter.deletedBackground": s.error,
    "editorGutter.addedSecondaryBackground": withAlpha(s.success, 0.5),
    "editorGutter.modifiedSecondaryBackground": withAlpha(s.info, 0.5),
    "editorGutter.deletedSecondaryBackground": withAlpha(s.error, 0.5),
    "editorGutter.foldingControlForeground": p.fgMuted,
    "editorGutter.itemBackground": withAlpha(p.accent, 0.14),
    "editorGutter.itemGlyphForeground": p.fg0,
    "editorGutter.commentGlyphForeground": p.accentSoft,
    "editorGutter.commentDraftGlyphForeground": withAlpha(p.accentSoft, 0.7),
    "editorGutter.commentUnresolvedGlyphForeground": s.warning,
    "editorGutter.commentRangeForeground": withAlpha(p.accent, 0.16),

    // ── Overview ruler ────────────────────────────────────────────────────
    "editorOverviewRuler.background": p.bg0,
    "editorOverviewRuler.addedForeground": withAlpha(s.success, 0.7),
    "editorOverviewRuler.modifiedForeground": withAlpha(s.info, 0.7),
    "editorOverviewRuler.deletedForeground": withAlpha(s.error, 0.7),
    "editorOverviewRuler.errorForeground": s.error,
    "editorOverviewRuler.warningForeground": s.warning,
    "editorOverviewRuler.infoForeground": s.info,
    "editorOverviewRuler.bracketMatchForeground": withAlpha(p.accentSoft, 0.6),
    "editorOverviewRuler.findMatchForeground": withAlpha(p.accent, 0.6),
    "editorOverviewRuler.rangeHighlightForeground": withAlpha(p.accent, 0.4),
    "editorOverviewRuler.selectionHighlightForeground": withAlpha(p.accent, 0.4),
    "editorOverviewRuler.wordHighlightForeground": withAlpha(p.accentSoft, 0.5),
    "editorOverviewRuler.wordHighlightStrongForeground": withAlpha(p.accentSoft, 0.65),
    "editorOverviewRuler.wordHighlightTextForeground": withAlpha(p.fg0, 0.4),
    "editorOverviewRuler.commonContentForeground": withAlpha(p.fgMuted, 0.4),
    "editorOverviewRuler.currentContentForeground": withAlpha(s.info, 0.6),
    "editorOverviewRuler.incomingContentForeground": withAlpha(s.success, 0.6),
    "editorOverviewRuler.commentForeground": withAlpha(p.accentSoft, 0.5),
    "editorOverviewRuler.commentDraftForeground": withAlpha(p.accentSoft, 0.35),
    "editorOverviewRuler.commentUnresolvedForeground": withAlpha(s.warning, 0.6),
    "editorOverviewRuler.inlineChatInserted": withAlpha(s.success, 0.5),
    "editorOverviewRuler.inlineChatRemoved": withAlpha(s.error, 0.5),

    // ── Suggest / hover / action list widgets ─────────────────────────────
    "editorSuggestWidget.background": surfaceHigh,
    "editorSuggestWidget.border": p.border,
    "editorSuggestWidget.foreground": p.fg1,
    "editorSuggestWidget.selectedBackground": activeBg,
    "editorSuggestWidget.selectedForeground": p.fg0,
    "editorSuggestWidget.selectedIconForeground": p.accent,
    "editorSuggestWidget.highlightForeground": p.accent,
    "editorSuggestWidget.focusHighlightForeground": p.accentSoft,
    "editorSuggestWidget.focusOutline": p.accent,
    "editorSuggestWidgetStatus.foreground": p.fgMuted,
    "editorHoverWidget.background": surfaceHigh,
    "editorHoverWidget.border": p.border,
    "editorHoverWidget.foreground": p.fg1,
    "editorHoverWidget.highlightForeground": p.accent,
    "editorHoverWidget.statusBarBackground": surface,
    "editorActionList.background": surfaceHigh,
    "editorActionList.foreground": p.fg1,
    "editorActionList.focusBackground": activeBg,
    "editorActionList.focusForeground": p.fg0,

    // ── Editor group / tabs ───────────────────────────────────────────────
    "editorGroup.dropBackground": dropBg,
    "editorGroup.emptyBackground": p.bg0,
    "editorGroup.focusedEmptyBorder": withAlpha(p.accent, 0.4),
    "editorGroup.dropIntoPromptBackground": surfaceHigh,
    "editorGroup.dropIntoPromptForeground": p.fg0,
    "editorGroup.dropIntoPromptBorder": p.accent,
    "editorGroupHeader.border": p.border,
    "editorGroupHeader.noTabsBackground": p.bg0,
    "tab.activeBorder": p.accent,
    "tab.hoverBorder": withAlpha(p.accent, 0.5),
    "tab.hoverForeground": p.fg0,
    "tab.activeModifiedBorder": s.warning,
    "tab.inactiveModifiedBorder": withAlpha(s.warning, 0.5),
    "tab.dragAndDropBorder": p.accent,
    "tab.lastPinnedBorder": subtleBorder,
    "tab.selectedBackground": activeBg,
    "tab.selectedForeground": p.fg0,
    "tab.selectedBorderTop": p.accent,
    "tab.unfocusedActiveBackground": surface,
    "tab.unfocusedActiveForeground": withAlpha(p.fg1, 0.8),
    "tab.unfocusedActiveBorder": withAlpha(p.accent, 0.5),
    "tab.unfocusedActiveModifiedBorder": withAlpha(s.warning, 0.6),
    "tab.unfocusedInactiveBackground": p.bg1,
    "tab.unfocusedInactiveForeground": withAlpha(p.fgMuted, 0.7),
    "tab.unfocusedInactiveModifiedBorder": withAlpha(s.warning, 0.4),
    "tab.unfocusedHoverBorder": withAlpha(p.accent, 0.3),
    "tab.unfocusedHoverForeground": p.fg1,
    "modernTab.activeBackground": activeBg,
    "modernTab.activeForeground": p.fg0,
    "modernTab.hoverBackground": hoverBg,
    "modernTab.hoverForeground": p.fg0,
    "modernEditorTab.activeBackground": activeBg,
    "modernEditorTab.activeForeground": p.fg0,
    "modernEditorTab.inactiveBackground": p.bg1,
    "modernEditorTab.hoverBackground": hoverBg,
    "modernEditorTab.hoverForeground": p.fg0,
    "modernEditorTab.activeHoverBackground": withAlpha(p.accent, 0.22),
    "modernEditorTab.activeActionBackground": activeBg,
    "modernEditorTab.activeHoverActionBackground": withAlpha(p.accent, 0.24),
    "modernEditorTab.hoverActionBackground": hoverBg,
    "modernEditorTab.selectedActionBackground": activeBg,
    "sideBySideEditor.horizontalBorder": p.border,
    "sideBySideEditor.verticalBorder": p.border,

    // ── Diff / merge ──────────────────────────────────────────────────────
    "diffEditor.border": p.border,
    "diffEditor.diagonalFill": withAlpha(p.border, 0.5),
    "diffEditor.insertedTextBackground": addedBg,
    "diffEditor.insertedLineBackground": addedLine,
    "diffEditor.insertedTextBorder": transparent,
    "diffEditor.removedTextBackground": removedBg,
    "diffEditor.removedLineBackground": removedLine,
    "diffEditor.removedTextBorder": transparent,
    "diffEditor.unchangedRegionBackground": p.bg1,
    "diffEditor.unchangedRegionForeground": p.fgMuted,
    "diffEditor.unchangedCodeBackground": withAlpha(p.fg0, 0.02),
    "diffEditor.unchangedRegionShadow": shadow,
    "diffEditor.move.border": withAlpha(p.huePurple, 0.6),
    "diffEditor.moveActive.border": p.huePurple,
    "diffEditorGutter.insertedLineBackground": withAlpha(s.success, 0.22),
    "diffEditorGutter.removedLineBackground": withAlpha(s.error, 0.22),
    "diffEditorOverview.insertedForeground": withAlpha(s.success, 0.6),
    "diffEditorOverview.removedForeground": withAlpha(s.error, 0.6),
    "merge.border": p.border,
    "merge.currentHeaderBackground": withAlpha(s.info, 0.3),
    "merge.currentContentBackground": withAlpha(s.info, 0.14),
    "merge.incomingHeaderBackground": withAlpha(s.success, 0.3),
    "merge.incomingContentBackground": withAlpha(s.success, 0.14),
    "merge.commonHeaderBackground": withAlpha(p.fgMuted, 0.24),
    "merge.commonContentBackground": withAlpha(p.fgMuted, 0.1),
    "mergeEditor.change.background": addedBg,
    "mergeEditor.change.word.background": withAlpha(s.success, 0.26),
    "mergeEditor.changeBase.background": withAlpha(p.fgMuted, 0.14),
    "mergeEditor.changeBase.word.background": withAlpha(p.fgMuted, 0.26),
    "mergeEditor.conflict.unhandledUnfocused.border": withAlpha(s.warning, 0.5),
    "mergeEditor.conflict.unhandledFocused.border": s.warning,
    "mergeEditor.conflict.handledUnfocused.border": withAlpha(s.success, 0.4),
    "mergeEditor.conflict.handledFocused.border": s.success,
    "mergeEditor.conflict.handled.minimapOverViewRuler": withAlpha(s.success, 0.6),
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": s.warning,
    "mergeEditor.conflict.input1.background": withAlpha(s.info, 0.16),
    "mergeEditor.conflict.input2.background": withAlpha(s.success, 0.16),
    "mergeEditor.conflictingLines.background": withAlpha(s.warning, 0.16),
    "multiDiffEditor.background": p.bg0,
    "multiDiffEditor.border": p.border,
    "multiDiffEditor.headerBackground": surface,

    // ── Peek view / marker navigation ─────────────────────────────────────
    "peekViewEditor.matchHighlightBorder": withAlpha(p.accent, 0.5),
    "peekViewEditorGutter.background": p.bg1,
    "peekViewEditorStickyScroll.background": surface,
    "peekViewEditorStickyScrollGutter.background": surface,
    "editorMarkerNavigation.background": surface,
    "editorMarkerNavigationError.background": s.error,
    "editorMarkerNavigationError.headerBackground": withAlpha(s.error, 0.18),
    "editorMarkerNavigationWarning.background": s.warning,
    "editorMarkerNavigationWarning.headerBackground": withAlpha(s.warning, 0.18),
    "editorMarkerNavigationInfo.background": s.info,
    "editorMarkerNavigationInfo.headerBackground": withAlpha(s.info, 0.18),

    // ── Indent guides (rainbow-capable, 1..6) ─────────────────────────────
    "editorIndentGuide.background1": withAlpha(p.border, 0.5),
    "editorIndentGuide.background2": withAlpha(p.hueBlue, 0.16),
    "editorIndentGuide.background3": withAlpha(p.hueCyan, 0.16),
    "editorIndentGuide.background4": withAlpha(p.hueGreen, 0.16),
    "editorIndentGuide.background5": withAlpha(p.hueYellow, 0.16),
    "editorIndentGuide.background6": withAlpha(p.huePurple, 0.16),
    "editorIndentGuide.activeBackground1": withAlpha(p.fgMuted, 0.5),
    "editorIndentGuide.activeBackground2": withAlpha(p.hueBlue, 0.45),
    "editorIndentGuide.activeBackground3": withAlpha(p.hueCyan, 0.45),
    "editorIndentGuide.activeBackground4": withAlpha(p.hueGreen, 0.45),
    "editorIndentGuide.activeBackground5": withAlpha(p.hueYellow, 0.45),
    "editorIndentGuide.activeBackground6": withAlpha(p.huePurple, 0.45),

    // ── Comments widget ───────────────────────────────────────────────────
    "editorCommentsWidget.resolvedBorder": withAlpha(s.success, 0.6),
    "editorCommentsWidget.unresolvedBorder": s.warning,
    "editorCommentsWidget.rangeBackground": withAlpha(p.accent, 0.1),
    "editorCommentsWidget.rangeActiveBackground": withAlpha(p.accent, 0.16),
    "editorCommentsWidget.replyInputBackground": surfaceHigh,
    "commentsView.resolvedIcon": withAlpha(s.success, 0.8),
    "commentsView.unresolvedIcon": s.warning,

    // ── Minimap ───────────────────────────────────────────────────────────
    "minimap.background": p.bg0,
    "minimap.foregroundOpacity": withAlpha(p.bg0, 0.75),
    "minimap.findMatchHighlight": withAlpha(p.accent, 0.55),
    "minimap.selectionHighlight": withAlpha(p.accentSoft, 0.5),
    "minimap.selectionOccurrenceHighlight": withAlpha(p.accentSoft, 0.35),
    "minimap.chatEditHighlight": withAlpha(p.huePurple, 0.4),
    "minimapGutter.deletedBackground": s.error,
    "editorMinimap.inlineChatInserted": withAlpha(s.success, 0.4),

    // ── Git decorations ───────────────────────────────────────────────────
    "gitDecoration.untrackedResourceForeground": s.success,
    "gitDecoration.ignoredResourceForeground": withAlpha(p.fgMuted, 0.55),
    "gitDecoration.conflictingResourceForeground": s.error,
    "gitDecoration.renamedResourceForeground": p.hueCyan,
    "gitDecoration.submoduleResourceForeground": p.huePurple,
    "gitDecoration.stageDeletedResourceForeground": withAlpha(s.error, 0.8),
    "git.blame.editorDecorationForeground": withAlpha(p.fgMuted, 0.6),

    // ── SCM graph ─────────────────────────────────────────────────────────
    "scmGraph.foreground1": p.hueBlue,
    "scmGraph.foreground2": p.hueGreen,
    "scmGraph.foreground3": p.hueOrange,
    "scmGraph.foreground4": p.huePurple,
    "scmGraph.foreground5": p.hueCyan,
    "scmGraph.historyItemRefColor": p.accent,
    "scmGraph.historyItemRemoteRefColor": p.hueCyan,
    "scmGraph.historyItemBaseRefColor": p.huePurple,
    "scmGraph.historyItemHoverLabelForeground": p.bg0,
    "scmGraph.historyItemHoverAdditionsForeground": s.success,
    "scmGraph.historyItemHoverDeletionsForeground": s.error,
    "scmGraph.historyItemHoverDefaultLabelBackground": withAlpha(p.fgMuted, 0.25),
    "scmGraph.historyItemHoverDefaultLabelForeground": p.fg0,

    // ── Lists / trees / quick input ───────────────────────────────────────
    "list.dropBackground": dropBg,
    "list.dropBetweenBackground": p.accent,
    "list.activeSelectionIconForeground": p.accent,
    "list.inactiveSelectionIconForeground": p.fgMuted,
    "list.deemphasizedForeground": withAlpha(p.fgMuted, 0.7),
    "list.invalidItemForeground": s.error,
    "list.filterMatchBackground": withAlpha(p.accent, 0.22),
    "list.filterMatchBorder": withAlpha(p.accent, 0.45),
    "list.focusHighlightForeground": p.accentSoft,
    "list.inactiveFocusOutline": withAlpha(p.accent, 0.3),
    "listFilterWidget.background": surfaceHigh,
    "listFilterWidget.outline": p.accent,
    "listFilterWidget.noMatchesOutline": s.error,
    "listFilterWidget.shadow": shadow,
    "tree.inactiveIndentGuidesStroke": withAlpha(p.border, 0.5),
    "tree.tableColumnsBorder": withAlpha(p.border, 0.6),
    "tree.tableOddRowsBackground": withAlpha(p.fg0, 0.02),
    "quickInput.background": surfaceHigh,
    "quickInput.foreground": p.fg1,
    "quickInputTitle.background": surface,
    "quickInput.list.focusBackground": activeBg,
    "quickInputList.focusBackground": activeBg,
    "quickInputList.focusForeground": p.fg0,
    "quickInputList.focusIconForeground": p.accent,
    "quickInputList.focusHighlightForeground": p.accentSoft,
    "pickerGroup.border": p.border,
    "pickerGroup.foreground": p.accentSoft,

    // ── Menus ─────────────────────────────────────────────────────────────
    "menu.background": surfaceHigh,
    "menu.foreground": p.fg1,
    "menu.border": p.border,
    "menu.selectionBackground": activeBg,
    "menu.selectionForeground": p.fg0,
    "menu.selectionBorder": transparent,
    "menu.separatorBackground": withAlpha(p.border, 0.7),
    "menubar.selectionBackground": activeBg,
    "menubar.selectionForeground": p.fg0,
    "menubar.selectionBorder": transparent,

    // ── Side bar / panel sections ─────────────────────────────────────────
    "sideBar.dropBackground": dropBg,
    "sideBarTitle.background": surface,
    "sideBarTitle.border": p.border,
    "sideBarSectionHeader.background": surfaceHigh,
    "sideBarSectionHeader.foreground": p.fg1,
    "sideBarSectionHeader.border": p.border,
    "sideBarStickyScroll.background": surface,
    "sideBarStickyScroll.border": p.border,
    "sideBarStickyScroll.shadow": shadow,
    "panel.dropBorder": p.accent,
    "panelInput.border": p.border,
    "panelSection.border": p.border,
    "panelSection.dropBackground": dropBg,
    "panelSectionHeader.background": surfaceHigh,
    "panelSectionHeader.foreground": p.fg1,
    "panelSectionHeader.border": p.border,
    "panelStickyScroll.background": surface,
    "panelStickyScroll.border": p.border,
    "panelStickyScroll.shadow": shadow,
    "panelTitle.border": p.border,
    "panelTitle.activeBorder": p.accent,
    "panelTitleBadge.background": p.accent,
    "panelTitleBadge.foreground": p.bg0,
    "outputView.background": p.bg0,
    "outputViewStickyScroll.background": surface,

    // ── Status bar ────────────────────────────────────────────────────────
    "statusBar.focusBorder": p.accent,
    "statusBar.debuggingBackground": p.hueOrange,
    "statusBar.debuggingForeground": p.bg0,
    "statusBar.debuggingBorder": withAlpha(p.hueOrange, 0.6),
    "statusBar.noFolderBackground": surfaceHigh,
    "statusBar.noFolderForeground": p.fg1,
    "statusBar.noFolderBorder": p.border,
    "statusBarItem.activeBackground": withAlpha(p.fg0, 0.16),
    "statusBarItem.hoverForeground": p.fg0,
    "statusBarItem.focusBorder": p.accent,
    "statusBarItem.compactHoverBackground": withAlpha(p.fg0, 0.2),
    "statusBarItem.prominentBackground": withAlpha(p.accent, 0.3),
    "statusBarItem.prominentForeground": p.fg0,
    "statusBarItem.prominentHoverBackground": withAlpha(p.accent, 0.4),
    "statusBarItem.prominentHoverForeground": p.fg0,
    "statusBarItem.remoteBackground": p.accent,
    "statusBarItem.remoteForeground": p.bg0,
    "statusBarItem.remoteHoverBackground": p.accentSoft,
    "statusBarItem.remoteHoverForeground": p.bg0,
    "statusBarItem.offlineBackground": s.error,
    "statusBarItem.offlineForeground": p.bg0,
    "statusBarItem.offlineHoverBackground": s.errorMuted,
    "statusBarItem.offlineHoverForeground": p.bg0,

    // ── Notifications / profiles / badges ─────────────────────────────────
    "notificationCenter.border": p.border,
    "notificationToast.border": p.border,
    "profileBadge.background": withAlpha(p.accent, 0.35),
    "profileBadge.foreground": p.fg0,
    "profiles.sashBorder": p.border,
    "extensionBadge.remoteBackground": p.accent,
    "extensionBadge.remoteForeground": p.bg0,
    "extensionButton.background": p.accent,
    "extensionButton.foreground": p.bg0,
    "extensionButton.border": transparent,
    "extensionButton.hoverBackground": p.accentSoft,
    "extensionButton.separator": withAlpha(p.bg0, 0.4),
    "extensionButton.prominentBackground": p.accent,
    "extensionButton.prominentForeground": p.bg0,
    "extensionButton.prominentHoverBackground": p.accentSoft,
    "extensionIcon.starForeground": p.hueYellow,
    "extensionIcon.verifiedForeground": s.info,
    "extensionIcon.preReleaseForeground": p.hueOrange,
    "extensionIcon.sponsorForeground": p.hueRed,
    "extensionIcon.privateForeground": p.fgMuted,
    "mcpIcon.starForeground": p.hueYellow,
    "ports.iconRunningProcessForeground": s.success,

    // ── Debug ─────────────────────────────────────────────────────────────
    "debugIcon.breakpointForeground": s.error,
    "debugIcon.breakpointDisabledForeground": withAlpha(s.error, 0.45),
    "debugIcon.breakpointUnverifiedForeground": withAlpha(p.fgMuted, 0.7),
    "debugIcon.breakpointCurrentStackframeForeground": p.hueYellow,
    "debugIcon.breakpointStackframeForeground": withAlpha(p.hueYellow, 0.7),
    "debugIcon.startForeground": s.success,
    "debugIcon.pauseForeground": s.info,
    "debugIcon.stopForeground": s.error,
    "debugIcon.disconnectForeground": s.error,
    "debugIcon.restartForeground": s.success,
    "debugIcon.stepOverForeground": p.accent,
    "debugIcon.stepIntoForeground": p.accent,
    "debugIcon.stepOutForeground": p.accent,
    "debugIcon.stepBackForeground": p.accent,
    "debugIcon.continueForeground": p.accent,
    "debugConsole.infoForeground": s.info,
    "debugConsole.warningForeground": s.warning,
    "debugConsole.errorForeground": s.error,
    "debugConsole.sourceForeground": p.fgMuted,
    "debugConsoleInputIcon.foreground": p.accent,
    "debugTokenExpression.name": p.hueBlue,
    "debugTokenExpression.value": p.fg1,
    "debugTokenExpression.string": p.hueGreen,
    "debugTokenExpression.number": p.hueOrange,
    "debugTokenExpression.boolean": p.huePurple,
    "debugTokenExpression.error": s.error,
    "debugTokenExpression.type": p.hueCyan,
    "debugView.stateLabelBackground": withAlpha(p.accent, 0.22),
    "debugView.stateLabelForeground": p.fg0,
    "debugView.exceptionLabelBackground": withAlpha(s.error, 0.3),
    "debugView.exceptionLabelForeground": p.fg0,
    "debugView.valueChangedHighlight": withAlpha(s.info, 0.5),
    "debugExceptionWidget.background": withAlpha(s.error, 0.16),
    "debugExceptionWidget.border": s.error,

    // ── Testing ───────────────────────────────────────────────────────────
    "testing.runAction": s.success,
    "testing.peekBorder": s.error,
    "testing.peekHeaderBackground": withAlpha(s.error, 0.14),
    "testing.messagePeekBorder": s.info,
    "testing.messagePeekHeaderBackground": withAlpha(s.info, 0.14),
    "testing.coveredBackground": withAlpha(s.success, 0.14),
    "testing.coveredBorder": withAlpha(s.success, 0.4),
    "testing.coveredGutterBackground": withAlpha(s.success, 0.4),
    "testing.coveredMinimapBackground": withAlpha(s.success, 0.4),
    "testing.uncoveredBackground": withAlpha(s.error, 0.12),
    "testing.uncoveredBorder": withAlpha(s.error, 0.35),
    "testing.uncoveredGutterBackground": withAlpha(s.error, 0.35),
    "testing.uncoveredMinimapBackground": withAlpha(s.error, 0.35),
    "testing.uncoveredBranchBackground": withAlpha(s.warning, 0.25),
    "testing.coverCountBadgeBackground": p.accent,
    "testing.coverCountBadgeForeground": p.bg0,

    // ── Notebook ──────────────────────────────────────────────────────────
    "notebook.editorBackground": p.bg0,
    "notebook.cellEditorBackground": p.bg1,
    "notebook.cellBorderColor": p.border,
    "notebook.cellHoverBackground": withAlpha(p.fg0, 0.03),
    "notebook.cellInsertionIndicator": p.accent,
    "notebook.cellStatusBarItemHoverBackground": hoverBg,
    "notebook.cellToolbarSeparator": withAlpha(p.border, 0.7),
    "notebook.focusedCellBackground": withAlpha(p.accent, 0.05),
    "notebook.focusedCellBorder": p.accent,
    "notebook.focusedEditorBorder": p.accent,
    "notebook.inactiveFocusedCellBorder": withAlpha(p.accent, 0.4),
    "notebook.inactiveSelectedCellBorder": withAlpha(p.accent, 0.25),
    "notebook.selectedCellBackground": withAlpha(p.accent, 0.08),
    "notebook.selectedCellBorder": withAlpha(p.accent, 0.5),
    "notebook.symbolHighlightBackground": withAlpha(p.hueYellow, 0.16),
    "notebook.outputContainerBackgroundColor": withAlpha(p.fg0, 0.02),
    "notebook.outputContainerBorderColor": withAlpha(p.border, 0.6),
    "notebookStatusSuccessIcon.foreground": s.success,
    "notebookStatusErrorIcon.foreground": s.error,
    "notebookStatusRunningIcon.foreground": s.info,
    "notebookEditorOverviewRuler.runningCellForeground": s.info,
    "notebookScrollbarSlider.background": withAlpha(p.fgMuted, 0.2),
    "notebookScrollbarSlider.hoverBackground": withAlpha(p.fgMuted, 0.3),
    "notebookScrollbarSlider.activeBackground": withAlpha(p.fgMuted, 0.4),

    // ── Chat / inline chat / AI surfaces ──────────────────────────────────
    "chat.requestBackground": withAlpha(p.fg0, 0.03),
    "chat.requestBorder": withAlpha(p.border, 0.6),
    "chat.requestBubbleBackground": withAlpha(p.fg0, 0.05),
    "chat.requestBubbleHoverBackground": withAlpha(p.fg0, 0.08),
    "chat.requestCodeBorder": p.border,
    "chat.slashCommandBackground": withAlpha(p.accent, 0.2),
    "chat.slashCommandForeground": p.accentSoft,
    "chat.avatarBackground": surfaceHigh,
    "chat.avatarForeground": p.fg1,
    "chat.editedFileForeground": s.warning,
    "chat.linesAddedForeground": s.success,
    "chat.linesRemovedForeground": s.error,
    "chat.checkpointSeparator": withAlpha(p.border, 0.7),
    "chat.thinkingShimmer": withAlpha(p.huePurple, 0.5),
    "chatManagement.sashBorder": p.border,
    "aiCustomizationManagement.sashBorder": p.border,
    "inlineChat.background": surfaceHigh,
    "inlineChat.foreground": p.fg1,
    "inlineChat.border": p.border,
    "inlineChat.shadow": shadow,
    "inlineChatInput.background": p.bg1,
    "inlineChatInput.border": p.border,
    "inlineChatInput.focusBorder": p.accent,
    "inlineChatInput.placeholderForeground": withAlpha(p.fgMuted, 0.7),
    "inlineChatDiff.inserted": addedLine,
    "inlineChatDiff.removed": removedLine,
    "agentSessionReadIndicator.foreground": withAlpha(p.fgMuted, 0.7),
    "agentSessionSelectedBadge.border": p.accent,
    "agentSessionSelectedUnfocusedBadge.border": withAlpha(p.accent, 0.5),
    "agentStatusIndicator.background": p.accent,
    "agentsVoice.speakingBackground": withAlpha(p.huePurple, 0.25),
    "agentsVoice.speakingForeground": p.huePurple,
    "interactive.activeCodeBorder": p.accent,
    "interactive.inactiveCodeBorder": withAlpha(p.border, 0.6),

    // ── Inline edit (NES) ─────────────────────────────────────────────────
    "inlineEdit.originalBackground": removedLine,
    "inlineEdit.originalBorder": withAlpha(s.error, 0.4),
    "inlineEdit.originalChangedLineBackground": removedLine,
    "inlineEdit.originalChangedTextBackground": removedBg,
    "inlineEdit.modifiedBackground": addedLine,
    "inlineEdit.modifiedBorder": withAlpha(s.success, 0.4),
    "inlineEdit.modifiedChangedLineBackground": addedLine,
    "inlineEdit.modifiedChangedTextBackground": addedBg,
    "inlineEdit.tabWillAcceptModifiedBorder": s.success,
    "inlineEdit.tabWillAcceptOriginalBorder": s.error,
    "inlineEdit.gutterIndicator.background": withAlpha(p.accent, 0.16),
    "inlineEdit.gutterIndicator.primaryBackground": p.accent,
    "inlineEdit.gutterIndicator.primaryForeground": p.bg0,
    "inlineEdit.gutterIndicator.primaryBorder": p.accent,
    "inlineEdit.gutterIndicator.secondaryBackground": withAlpha(p.accent, 0.3),
    "inlineEdit.gutterIndicator.secondaryForeground": p.fg0,
    "inlineEdit.gutterIndicator.secondaryBorder": withAlpha(p.accent, 0.5),

    // ── Terminal extras ───────────────────────────────────────────────────
    "terminal.border": p.border,
    "terminal.selectionBackground": p.selection,
    "terminal.selectionForeground": p.fg0,
    "terminal.inactiveSelectionBackground": withAlpha(p.selection, 0.6),
    "terminal.hoverHighlightBackground": withAlpha(p.accent, 0.14),
    "terminal.dropBackground": dropBg,
    "terminal.initialHintForeground": withAlpha(p.fgMuted, 0.6),
    "terminal.tab.activeBorder": p.accent,
    "terminalCursor.foreground": p.accentSoft,
    "terminalCursor.background": p.bg0,
    "terminalCommandDecoration.defaultBackground": withAlpha(p.fgMuted, 0.5),
    "terminalCommandGuide.foreground": withAlpha(p.accent, 0.4),
    "terminalOverviewRuler.border": p.border,
    "terminalOverviewRuler.cursorForeground": p.accentSoft,
    "terminalOverviewRuler.findMatchForeground": withAlpha(p.accent, 0.6),
    "terminalStickyScroll.background": surface,
    "terminalStickyScroll.border": p.border,
    "terminalStickyScrollHover.background": surfaceHigh,

    // ── Terminal suggest-widget symbol icons ──────────────────────────────
    "terminalSymbolIcon.fileForeground": p.fg1,
    "terminalSymbolIcon.folderForeground": p.accent,
    "terminalSymbolIcon.methodForeground": p.hueBlue,
    "terminalSymbolIcon.aliasForeground": p.hueCyan,
    "terminalSymbolIcon.argumentForeground": p.hueOrange,
    "terminalSymbolIcon.optionForeground": p.huePurple,
    "terminalSymbolIcon.optionValueForeground": p.hueGreen,
    "terminalSymbolIcon.flagForeground": p.huePurple,
    "terminalSymbolIcon.branchForeground": p.hueGreen,
    "terminalSymbolIcon.commitForeground": p.hueYellow,
    "terminalSymbolIcon.tagForeground": p.hueOrange,
    "terminalSymbolIcon.stashForeground": p.hueCyan,
    "terminalSymbolIcon.remoteForeground": p.hueBlue,
    "terminalSymbolIcon.pullRequestForeground": p.hueOrange,
    "terminalSymbolIcon.pullRequestDoneForeground": p.hueGreen,
    "terminalSymbolIcon.symbolicLinkFileForeground": p.hueCyan,
    "terminalSymbolIcon.symbolicLinkFolderForeground": p.hueCyan,
    "terminalSymbolIcon.inlineSuggestionForeground": withAlpha(p.fgMuted, 0.7),
    "terminalSymbolIcon.symbolText": p.fg1,

    // ── Remaining editor widgets ──────────────────────────────────────────
    "editorWidget.resizeBorder": p.accent,
    "editorUnnecessaryCode.border": transparent,
    // Expressed as an alpha-only color: VS Code uses the alpha channel to fade
    // unreachable code rather than tinting it.
    "editorUnnecessaryCode.opacity": withAlpha(p.bg0, 0.67),

    // ── Text / markdown surfaces ──────────────────────────────────────────
    "textBlockQuote.background": withAlpha(p.fg0, 0.03),
    "textBlockQuote.border": withAlpha(p.accent, 0.5),
    "textCodeBlock.background": withAlpha(p.fg0, 0.05),
    "textLink.foreground": p.accent,
    "textLink.activeForeground": p.accentSoft,
    "textPreformat.foreground": p.hueOrange,
    "textPreformat.background": withAlpha(p.hueOrange, 0.1),
    "textPreformat.border": transparent,
    "textSeparator.foreground": withAlpha(p.border, 0.8),
    "walkThrough.embeddedEditorBackground": p.bg1,
    "walkthrough.stepTitle.foreground": p.fg0,

    // ── Charts / gauge ────────────────────────────────────────────────────
    "chart.line": p.accent,
    "chart.axis": withAlpha(p.fgMuted, 0.6),
    "chart.guide": withAlpha(p.border, 0.6),
    "charts.foreground": p.fg1,
    "charts.lines": withAlpha(p.border, 0.6),
    "charts.red": p.hueRed,
    "charts.orange": p.hueOrange,
    "charts.yellow": p.hueYellow,
    "charts.green": p.hueGreen,
    "charts.blue": p.hueBlue,
    "charts.purple": p.huePurple,
    "gauge.background": withAlpha(p.accent, 0.2),
    "gauge.foreground": p.accent,
    "gauge.border": withAlpha(p.accent, 0.5),

    // ── Search / settings / misc ──────────────────────────────────────────
    "search.resultsInfoForeground": p.fgMuted,
    "searchEditor.findMatchBackground": withAlpha(p.accent, 0.22),
    "searchEditor.findMatchBorder": withAlpha(p.accent, 0.4),
    "searchEditor.textInputBorder": p.border,
    "settings.headerBorder": p.border,
    "settings.sashBorder": p.border,
    "settings.focusedRowBackground": withAlpha(p.accent, 0.06),
    "settings.focusedRowBorder": withAlpha(p.accent, 0.4),
    "settings.rowHoverBackground": withAlpha(p.fg0, 0.03),
    "settings.dropdownListBorder": p.border,
    "settings.settingsHeaderHoverForeground": p.fg0,
    "simpleFindWidget.sashBorder": p.border,
    "scrollbar.background": transparent,
    "browser.border": p.border,
    "surface.background": surface,
    "surface.foreground": p.fg1,
    "surface.border": p.border,
    strongForeground: p.fg0,
    disabledForeground: withAlpha(p.fgMuted, 0.5),
  };
}
