/**
 * Atmosphere & tone-grading bricks — cinematic depth and colour arcs.
 *
 * atmosphereBrick  — procedural fog layer: turbulence → alpha-mask → gaussian blur → flood+composite.
 *                   Creates organic fog/haze patches that have no visible rectangular boundary.
 *
 * toneCurveBrick   — cinematic gradient vignette: darkens top/bottom edges with a
 *                   preset-specific hue to simulate tone-curve feels. Uses normal blend.
 *
 * blendLayerBrick  — full-viewport rect with SVG mix-blend-mode (screen, overlay, soft-light…).
 */
import type { BrickOutput, BrickParams } from "../types.js";

// ─── Atmosphere Brick ────────────────────────────────────────────────────────

export interface AtmosphereBrickOptions {
  id?: string;
  /** Base fill colour for the haze layer */
  color: string;
  /** Highlight colour (unused — kept for API compatibility) */
  highlightColor?: string;
  /** feTurbulence base frequency (lower = larger fog swirls) */
  turbulenceFreq?: number;
  /** Controls soft-blur radius for fog edges (fraction of scale) */
  displacementScale?: number;
  /** Unused — kept for API compatibility */
  lightElevation?: number;
  /** Unused — kept for API compatibility */
  lightAzimuth?: number;
  /** Unused — kept for API compatibility */
  surfaceScale?: number;
  /** Overall opacity of the fog patches */
  opacity?: number;
  /** Turbulence seed for variety across motifs */
  seed?: number;
}

/**
 * Organic procedural fog layer with NO visible rectangular boundary.
 *
 * Filter chain:
 *   1. feTurbulence (fractalNoise) — generates large-scale noise
 *   2. feColorMatrix — extracts noise luminance as an alpha fog-density mask
 *   3. feGaussianBlur — softens fog patch edges significantly
 *   4. feFlood — provides the atmosphere hue
 *   5. feComposite (in) — clips flood colour to where the fog mask has alpha
 *
 * The source rect uses fill="transparent" so the filter entirely controls output shape.
 * Resulting patches are soft, organic, and merge invisibly into dark backgrounds.
 */
export function atmosphereBrick(params: BrickParams, options: AtmosphereBrickOptions): BrickOutput {
  const { viewBox } = params;
  const { width, height } = viewBox;
  const scale = Math.max(width, height);
  const {
    color,
    highlightColor,
    turbulenceFreq = 0.003,
    displacementScale = 0.025,
    opacity = 0.25,
    seed = 7,
    id = "atmo",
  } = options;

  // Blur radius — feathers fog patch edges so they blend invisibly into dark sky
  const blurSd = Math.min(displacementScale * scale, 90).toFixed(1);
  // Different X/Y frequency produces elongated horizontal sky formations
  const freqX = turbulenceFreq.toFixed(4);
  const freqY = (turbulenceFreq * 0.55).toFixed(4);
  const detailFreqX = (turbulenceFreq * 2.4).toFixed(4);
  const detailFreqY = (turbulenceFreq * 1.35).toFixed(4);
  const highlightOpacity = (opacity * 0.42).toFixed(3);
  const highlightBlur = Math.max(6, Number(blurSd) * 0.45).toFixed(1);
  const highlightPass = highlightColor
    ? `
  <feFlood flood-color="${highlightColor}" flood-opacity="${highlightOpacity}" result="HIGHLIGHTFILL"/>
  <feComposite in="HIGHLIGHTFILL" in2="SOFTMASK" operator="in" result="HIGHLIGHTMASKED"/>
  <feGaussianBlur in="HIGHLIGHTMASKED" stdDeviation="${highlightBlur}" result="HIGHLIGHTSOFT"/>
  <feBlend in="BASEHAZE" in2="HIGHLIGHTSOFT" mode="screen"/>`
    : "";

  const defs = `<filter id="${id}-f" x="-35%" y="-35%" width="170%" height="170%" color-interpolation-filters="sRGB">
  <feTurbulence type="fractalNoise" baseFrequency="${freqX} ${freqY}" numOctaves="5" seed="${seed}" result="MACRO"/>
  <feTurbulence type="fractalNoise" baseFrequency="${detailFreqX} ${detailFreqY}" numOctaves="3" seed="${seed + 17}" result="DETAIL"/>
  <feBlend in="MACRO" in2="DETAIL" mode="multiply" result="NOISE"/>
  <!-- Stronger threshold extraction for visibly defined fog clumps -->
  <feColorMatrix type="matrix" in="NOISE" result="ALPHAMASK"
    values="0 0 0 0 0
            0 0 0 0 0
            0 0 0 0 0
            0.62 0.48 0.38 0 -0.22"/>
  <!-- Soften fog patch edges -->
  <feGaussianBlur in="ALPHAMASK" stdDeviation="${blurSd}" result="SOFTMASK"/>
  <!-- Apply atmosphere colour only where fog density is non-zero -->
  <feFlood flood-color="${color}" flood-opacity="${opacity}" result="COLORFILL"/>
  <feComposite in="COLORFILL" in2="SOFTMASK" operator="in" result="BASEHAZE"/>${highlightPass}
</filter>`;

  // fill="transparent" — all visual content is generated by the filter from noise, not from the rect fill
  const elements = `<rect id="${id}" width="${width}" height="${height}" fill="transparent" filter="url(#${id}-f)"/>`;
  return { defs, elements };
}

// ─── Tone Curve Brick ────────────────────────────────────────────────────────

type TonePreset = "cinematic" | "film-fade" | "night-vision" | "custom";

export interface ToneCurveBrickOptions {
  id?: string;
  /** Preset look for the vignette gradient overlay */
  preset?: TonePreset;
  /** Overall layer opacity — lower = subtler */
  opacity?: number;
  // For preset="custom" — provide gradient stops override:
  tableR?: string;
  tableG?: string;
  tableB?: string;
  tableA?: string;
}

/**
 * Cinematic gradient vignette overlay.
 *
 * SVG feComponentTransfer on a rect cannot affect background content behind it,
 * so this brick instead renders a preset-specific gradient that approximates
 * cinematic tone-curve feels:
 *   - "cinematic"    : deep blue-black top+bottom shadow, letterbox-style depth
 *   - "film-fade"    : warm sepia-tinged top/bottom darkening
 *   - "night-vision" : cool green-black vignette framing
 *
 * Applied with normal blend at low opacity so it darkens/tints scene edges
 * without visibly obscuring sky or terrain details.
 */
export function toneCurveBrick(
  params: BrickParams,
  options: ToneCurveBrickOptions = {}
): BrickOutput {
  const { viewBox } = params;
  const { width, height } = viewBox;
  const { preset = "cinematic", opacity = 0.25, id = "tone" } = options;

  // Gradient specs per preset: creates directional darkening that reads as colour grade
  type GradSpec = {
    top: string;
    topOp: number;
    mid: string;
    midOp: number;
    bot: string;
    botOp: number;
  };

  const PRESETS: Record<Exclude<TonePreset, "custom">, GradSpec> = {
    cinematic: {
      top: "#030810",
      topOp: 0.55,
      mid: "#000000",
      midOp: 0.0,
      bot: "#040810",
      botOp: 0.5,
    },
    "film-fade": {
      top: "#100a06",
      topOp: 0.45,
      mid: "#080504",
      midOp: 0.05,
      bot: "#100c08",
      botOp: 0.4,
    },
    "night-vision": {
      top: "#001204",
      topOp: 0.5,
      mid: "#001008",
      midOp: 0.0,
      bot: "#001204",
      botOp: 0.45,
    },
  };

  const spec = preset === "custom" ? PRESETS.cinematic : PRESETS[preset];

  const defs = `<linearGradient id="${id}-g" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0%"   stop-color="${spec.top}" stop-opacity="${spec.topOp}"/>
  <stop offset="30%"  stop-color="${spec.mid}" stop-opacity="${spec.midOp}"/>
  <stop offset="70%"  stop-color="${spec.mid}" stop-opacity="${spec.midOp}"/>
  <stop offset="100%" stop-color="${spec.bot}" stop-opacity="${spec.botOp}"/>
</linearGradient>`;

  const elements = `<rect id="${id}" width="${width}" height="${height}" fill="url(#${id}-g)" opacity="${opacity}"/>`;
  return { defs, elements };
}

// ─── Blend Layer Brick ───────────────────────────────────────────────────────

type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "hard-light"
  | "soft-light"
  | "difference"
  | "exclusion"
  | "color-dodge"
  | "color-burn";

interface GradientStop {
  offset: string;
  color: string;
  opacity?: number;
}

interface RadialGradientSpec {
  type: "radial";
  cx?: number;
  cy?: number;
  r?: number;
  stops: GradientStop[];
}

interface LinearGradientSpec {
  type: "linear";
  angle?: number;
  stops: GradientStop[];
}

export interface BlendLayerBrickOptions {
  id?: string;
  color: string;
  blendMode?: BlendMode;
  opacity?: number;
  gradient?: RadialGradientSpec | LinearGradientSpec;
}

/**
 * Layer with SVG mix-blend-mode for advanced compositing.
 * Screen mode adds light without washing out; overlay adds contrast;
 * soft-light adds subtle colour tinting; color-dodge creates intense highlights.
 */
export function blendLayerBrick(params: BrickParams, options: BlendLayerBrickOptions): BrickOutput {
  const { viewBox } = params;
  const { width, height } = viewBox;
  const { color, blendMode = "screen", opacity = 0.2, id = "blend" } = options;

  const defs: string[] = [];
  let fillAttr = `fill="${color}"`;

  if (options.gradient) {
    const gr = options.gradient;
    if (gr.type === "radial") {
      const cx = ((gr.cx ?? 0.5) * width).toFixed(0);
      const cy = ((gr.cy ?? 0.5) * height).toFixed(0);
      const r = ((gr.r ?? 0.5) * Math.max(width, height)).toFixed(0);
      const stops = gr.stops
        .map(
          s =>
            `  <stop offset="${s.offset}" stop-color="${s.color}" stop-opacity="${s.opacity ?? 1}"/>`
        )
        .join("\n");
      defs.push(
        `<radialGradient id="${id}-g" cx="${cx}" cy="${cy}" r="${r}" gradientUnits="userSpaceOnUse">\n${stops}\n</radialGradient>`
      );
      fillAttr = `fill="url(#${id}-g)"`;
    } else {
      const angle = gr.angle ?? 180;
      const rad = ((angle - 90) * Math.PI) / 180;
      const x1 = (50 - 50 * Math.cos(rad)).toFixed(2);
      const y1 = (50 - 50 * Math.sin(rad)).toFixed(2);
      const x2 = (50 + 50 * Math.cos(rad)).toFixed(2);
      const y2 = (50 + 50 * Math.sin(rad)).toFixed(2);
      const stops = gr.stops
        .map(
          s =>
            `  <stop offset="${s.offset}" stop-color="${s.color}" stop-opacity="${s.opacity ?? 1}"/>`
        )
        .join("\n");
      defs.push(
        `<linearGradient id="${id}-g" x1="${x1}%" y1="${y1}%" x2="${x2}%" y2="${y2}%">\n${stops}\n</linearGradient>`
      );
      fillAttr = `fill="url(#${id}-g)"`;
    }
  }

  const elements = `<rect id="${id}" width="${width}" height="${height}" ${fillAttr} opacity="${opacity}" style="mix-blend-mode:${blendMode}"/>`;
  return { defs: defs.length > 0 ? defs.join("\n") : undefined, elements };
}
