/**
 * useTheme Composable
 * Manages theme selection, loading, and CSS variable injection
 */

import { computed, type Ref, ref, watch } from "vue";
import type { ThemeHarmony, ThemeIndex, ThemeIndexEntry } from "../types/theme.js";
import { sortHarmonies } from "../utils/harmony-utils.js";

// Theme state
const themeIndex: Ref<ThemeIndex | null> = ref(null);
const currentThemeKey = ref<string>("");
const isLoading = ref(true);
const error = ref<Error | null>(null);

/**
 * Convert hex color to RGB components
 */
function hexToRgb(hex?: string | null): string {
  if (!hex) return "0, 0, 0";
  const normalized = hex.trim().replace(/^#/, "");
  // Accept #RRGGBB and #RRGGBBAA (alpha ignored for RGB components)
  const rgbHex = normalized.length === 8 ? normalized.slice(0, 6) : normalized;
  const result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(rgbHex);
  if (!result) return "0, 0, 0";
  const r = Number.parseInt(result[1], 16);
  const g = Number.parseInt(result[2], 16);
  const b = Number.parseInt(result[3], 16);
  return `${r}, ${g}, ${b}`;
}

export function useTheme() {
  const humanizeId = (id: string) => {
    return id
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2")
      .trim();
  };
  /**
   * Load theme index from generated JSON
   */
  const baseUrl = import.meta.env.BASE_URL || "/";
  const loadThemeIndex = async () => {
    try {
      isLoading.value = true;
      error.value = null;

      console.log("[useTheme] Starting theme index load...");

      // Import theme index generated by build process
      const manifestUrl = `${baseUrl}themes-manifest.json`;
      console.log(`[useTheme] Fetching from: ${manifestUrl}`);

      const response = await fetch(manifestUrl);
      console.log(`[useTheme] Fetch response status: ${response.status}`);

      if (!response.ok) {
        throw new Error(`Failed to load theme index: ${response.statusText}`);
      }

      const data = await response.json();
      console.log(`[useTheme] Manifest loaded, theme count: ${Object.keys(data.themes).length}`);

      themeIndex.value = data;

      // Set default theme
      currentThemeKey.value = data.defaultThemeKey;
      console.log(`[useTheme] Default theme set to: ${currentThemeKey.value}`);

      // Apply theme colors to CSS variables
      console.log("[useTheme] Applying theme colors...");
      applyTheme(currentThemeKey.value);
      console.log("[useTheme] Theme applied successfully");
    } catch (err) {
      error.value = err instanceof Error ? err : new Error(String(err));
      console.error("[useTheme] Failed to load theme index:", err);
      console.error("[useTheme] Error details:", {
        message: error.value?.message,
        stack: error.value?.stack,
      });
    } finally {
      isLoading.value = false;
    }
  };

  /**
   * Apply theme colors to CSS custom properties
   */
  const applyTheme = (themeKey: string) => {
    if (!themeIndex.value) {
      console.error("[applyTheme] Theme index is null!");
      return;
    }

    const theme = themeIndex.value.themes[themeKey];
    if (!theme) {
      console.error("[applyTheme] Theme not found:", themeKey);
      return;
    }

    console.log("[applyTheme] Applying theme:", themeKey);
    console.log("[applyTheme] Theme colors:", theme.colors);

    const root = document.documentElement;
    const { colors } = theme;

    // Background colors (original variable names for compatibility)
    root.style.setProperty("--bg0", colors.bg0);
    root.style.setProperty("--bg1", colors.bg1);
    root.style.setProperty("--bg2", colors.bg2);

    console.log("[applyTheme] Set background colors:", {
      bg0: root.style.getPropertyValue("--bg0"),
      bg1: root.style.getPropertyValue("--bg1"),
      bg2: root.style.getPropertyValue("--bg2"),
    });

    // Background colors (HTML preview naming)
    root.style.setProperty("--bg-primary", colors.bg0);
    root.style.setProperty("--bg-secondary", colors.bg1);
    root.style.setProperty("--bg-tertiary", colors.bg2);

    // Foreground/text colors (original)
    root.style.setProperty("--fg0", colors.fg0);
    root.style.setProperty("--fg1", colors.fg1);
    root.style.setProperty("--fg-muted", colors.fgMuted);

    // Foreground/text colors (HTML preview naming)
    // Align with semantic typography tokens (chromatic, not neutral fg0/fg1)
    root.style.setProperty("--text-primary", colors.types);
    root.style.setProperty("--text-secondary", colors.functions);
    root.style.setProperty(
      "--text-muted",
      `color-mix(in oklab, ${colors.types} 65%, ${colors.bg1} 35%)`
    );
    root.style.setProperty("--text-strong", colors.keywords);
    root.style.setProperty(
      "--text-subtle",
      `color-mix(in oklab, ${colors.functions} 60%, ${colors.bg1} 40%)`
    );
    root.style.setProperty(
      "--text-disabled",
      `color-mix(in oklab, ${colors.fg0} 40%, ${colors.bg0} 60%)`
    );

    // Accent color (both conventions)
    root.style.setProperty("--accent", colors.accent);
    root.style.setProperty("--color-accent", colors.accent);
    root.style.setProperty("--syntax-accent", colors.accent);
    root.style.setProperty("--accent-rgb", hexToRgb(colors.accent));

    // Error color
    root.style.setProperty("--error", colors.error);
    root.style.setProperty("--color-error", colors.error);

    // Semantic state colors derived from theme palette
    // Warning: Use types/keywords color (typically yellow/orange in themes)
    root.style.setProperty("--color-warning", colors.keywords);
    // Success: Use strings/functions color (typically green/cyan in themes)
    root.style.setProperty("--color-success", colors.strings);
    // Info: Use accent color
    root.style.setProperty("--color-info", colors.accent);

    // RGB variants for rgba() usage
    root.style.setProperty("--bg0-rgb", hexToRgb(colors.bg0));
    root.style.setProperty("--bg1-rgb", hexToRgb(colors.bg1));
    root.style.setProperty("--bg2-rgb", hexToRgb(colors.bg2));
    root.style.setProperty("--fg0-rgb", hexToRgb(colors.fg0));
    root.style.setProperty("--fg1-rgb", hexToRgb(colors.fg1));
    root.style.setProperty("--fg-muted-rgb", hexToRgb(colors.fgMuted));
    root.style.setProperty("--color-error-rgb", hexToRgb(colors.error));
    root.style.setProperty("--color-warning-rgb", hexToRgb(colors.keywords));
    root.style.setProperty("--color-success-rgb", hexToRgb(colors.strings));

    // Syntax highlighting colors
    root.style.setProperty("--syntax-keywords", colors.keywords);
    root.style.setProperty("--syntax-types", colors.types);
    root.style.setProperty("--syntax-functions", colors.functions);
    root.style.setProperty("--syntax-strings", colors.strings);
    root.style.setProperty("--syntax-decorator", colors.decorator);
    root.style.setProperty("--syntax-error", colors.error);

    // Syntax RGB variants for rgba() usage
    root.style.setProperty("--syntax-keywords-rgb", hexToRgb(colors.keywords));
    root.style.setProperty("--syntax-types-rgb", hexToRgb(colors.types));
    root.style.setProperty("--syntax-functions-rgb", hexToRgb(colors.functions));
    root.style.setProperty("--syntax-strings-rgb", hexToRgb(colors.strings));
    root.style.setProperty("--syntax-decorator-rgb", hexToRgb(colors.decorator));

    // App typography (palette-driven, deliberately chromatic)
    // Avoid using fg0/fgMuted directly for UI text because some themes encode them as low-chroma and/or with alpha.
    root.style.setProperty("--app-text-primary", colors.types);
    root.style.setProperty("--app-text-strong", colors.keywords);
    root.style.setProperty(
      "--app-text-muted",
      `color-mix(in oklab, ${colors.types} 65%, ${colors.bg1} 35%)`
    );
    root.style.setProperty(
      "--app-text-subtle",
      `color-mix(in oklab, ${colors.functions} 60%, ${colors.bg1} 40%)`
    );
    root.style.setProperty(
      "--app-surface-border",
      `color-mix(in oklab, ${colors.accent} 30%, ${colors.bg0} 70%)`
    );
    root.style.setProperty(
      "--app-surface-border-strong",
      `color-mix(in oklab, ${colors.accent} 45%, ${colors.bg0} 55%)`
    );

    // Border colors (palette-driven, avoid fixed white/black/grey)
    root.style.setProperty("--border-color", "var(--app-surface-border)");
    root.style.setProperty("--border-primary", "var(--app-surface-border)");
    root.style.setProperty("--border-secondary", "var(--app-surface-border-strong)");

    // VS Code mock UI colors (all palette-derived)
    root.style.setProperty("--vscode-titlebar-bg", colors.bg1);
    // Keep the mock fully palette-driven but avoid neutral-looking foregrounds.
    root.style.setProperty("--vscode-titlebar-fg", colors.accent);
    root.style.setProperty("--vscode-tab-bg", colors.bg2);
    root.style.setProperty("--vscode-tab-fg", colors.functions);
    root.style.setProperty("--vscode-sidebar-bg", colors.bg1);
    root.style.setProperty("--vscode-sidebar-fg", colors.functions);
    root.style.setProperty("--vscode-editor-bg", colors.bg0);
    // Base code text should be chromatic (not gray): use a primary syntax hue.
    root.style.setProperty("--vscode-editor-fg", colors.types);
    root.style.setProperty("--vscode-statusbar-bg", colors.bg2);
    root.style.setProperty("--vscode-statusbar-fg", colors.keywords);
    root.style.setProperty("--vscode-statusbar-accent", colors.accent);

    // VS Code mock: make “secondary” code/UI bits use palette tokens (not gray fgMuted)
    root.style.setProperty("--vscode-syntax-punct", colors.types);
    root.style.setProperty("--vscode-syntax-comment", colors.decorator);
    root.style.setProperty("--vscode-statusbar-sep", colors.decorator);

    // Titlebar window controls (replace fixed macOS reds/yellows/greens)
    root.style.setProperty("--vscode-window-close", colors.error);
    root.style.setProperty("--vscode-window-minimize", colors.decorator);
    root.style.setProperty("--vscode-window-maximize", colors.functions);

    // Store in localStorage
    localStorage.setItem("caligo-site-theme", themeKey);
  };

  /**
   * Set active theme
   */
  const setTheme = (themeKey: string) => {
    if (!themeIndex.value?.themes[themeKey]) {
      console.warn(`Invalid theme key: ${themeKey}`);
      return;
    }

    currentThemeKey.value = themeKey;
    applyTheme(themeKey);
  };

  /**
   * Get current theme data
   */
  const currentTheme = computed<ThemeIndexEntry | null>(() => {
    if (!themeIndex.value || !currentThemeKey.value) return null;
    return themeIndex.value.themes[currentThemeKey.value] || null;
  });

  /**
   * Get all themes as array
   */
  const themes = computed<ThemeIndexEntry[]>(() => {
    if (!themeIndex.value) return [];
    return Object.values(themeIndex.value.themes);
  });

  /**
   * Ordered harmonies from manifest (fallback to canonical ordering)
   */
  const harmonies = computed(() => {
    const fallback: ThemeHarmony[] = [
      { id: "balanced", label: "Balanced" },
      { id: "analogous", label: "Analogous" },
      { id: "monochromatic", label: "Monochromatic" },
      { id: "split-complementary", label: "Split-Complementary" },
      { id: "triadic", label: "Triadic" },
    ];

    return sortHarmonies(themeIndex.value?.harmonies ?? fallback);
  });

  /**
   * Ordered seeds from manifest (fallback to stable list)
   */
  const seeds = computed(() => {
    const fallback = [
      { id: "AuroraNoir", slug: "auroranoir", label: "Aurora Noir" },
      { id: "Cinder", slug: "cinder", label: "Cinder" },
      { id: "DeepSable", slug: "deepsable", label: "Deep Sable" },
      { id: "Eclipse", slug: "eclipse", label: "Eclipse" },
      { id: "GraphiteFlux", slug: "graphiteflux", label: "Graphite Flux" },
      { id: "Mandarian", slug: "mandarian", label: "Mandarian" },
      { id: "MidnightAtelier", slug: "midnightatelier", label: "Midnight Atelier" },
      { id: "NebulaNight", slug: "nebulanight", label: "Nebula Night" },
      { id: "ObsidianGlow", slug: "obsidianglow", label: "Obsidian Glow" },
      { id: "VoidEmber", slug: "voidember", label: "Void Ember" },
    ];

    const fromManifest = themeIndex.value?.seeds ?? fallback;
    return fromManifest.map(seed => ({
      ...seed,
      label: seed.label && seed.label !== seed.id ? seed.label : humanizeId(seed.id),
    }));
  });

  /**
   * Get themes grouped by seed
   */
  const themesBySeed = computed(() => {
    if (!themeIndex.value) return {};

    const grouped: Record<string, ThemeIndexEntry[]> = {};

    for (const theme of themes.value) {
      if (!grouped[theme.seedId]) {
        grouped[theme.seedId] = [];
      }
      grouped[theme.seedId].push(theme);
    }

    return grouped;
  });

  /**
   * Watch for theme changes
   */
  watch(currentThemeKey, newKey => {
    if (newKey && themeIndex.value?.themes[newKey]) {
      applyTheme(newKey);
    }
  });

  return {
    // State
    themeIndex,
    currentThemeKey,
    currentTheme,
    themes,
    harmonies,
    seeds,
    themesBySeed,
    isLoading,
    error,

    // Actions
    loadThemeIndex,
    setTheme,
    setCurrentTheme: setTheme, // Alias for consistency
  };
}
